const fs = require('fs');
const path = require('path');

const basePath = path.join(__dirname, 'src/modules/business/accounting');

const files = {
  // Events
  'events/financial-report-exported.event.ts': `import { DomainEvent } from './domain-event.interface';
import { randomUUID } from 'crypto';

export class FinancialReportExportedEvent implements DomainEvent {
  event_id = randomUUID();
  event_name = 'FINANCIAL_REPORT_EXPORTED';
  occurred_at = new Date();
  entity_type = 'REPORT_EXPORT';

  constructor(public store_id: number, public tenant_id: number, public user_id: number, public entity_id: string, public correlation_id: string, public payload: any) {}
}
`,

  // Interfaces
  'interfaces/financial-export.interface.ts': `export interface ReportMetadata {
  company_name: string;
  report_name: string;
  fiscal_period: string;
  generated_by: string;
  generated_date: Date;
  orientation?: 'portrait' | 'landscape';
}

export interface ExportRequest {
  format: 'JSON' | 'CSV' | 'EXCEL' | 'PDF';
  report_type: 'TRIAL_BALANCE' | 'GENERAL_LEDGER' | 'PROFIT_LOSS' | 'BALANCE_SHEET' | 'CASH_FLOW';
  metadata: ReportMetadata;
  data: any;
}

export interface ExportResult {
  format: string;
  mime_type: string;
  file_name: string;
  content: string | Buffer;
}
`,

  // Services
  'services/financial-export.service.ts': `import { Injectable, BadRequestException } from '@nestjs/common';
import { DomainEventBusService } from '../events/domain-event-bus.service';
import { FinancialReportExportedEvent } from '../events/financial-report-exported.event';
import { ExportRequest, ExportResult } from '../interfaces/financial-export.interface';

@Injectable()
export class FinancialExportService {
  constructor(private readonly eventBus: DomainEventBusService) {}

  async generateExport(request: ExportRequest, storeId: number, userId: number): Promise<ExportResult> {
    let result: ExportResult;

    switch (request.format) {
      case 'JSON':
        result = this.generateJson(request);
        break;
      case 'CSV':
        result = this.generateCsv(request);
        break;
      case 'EXCEL':
      case 'PDF':
        // Future ready placeholder
        result = this.generateStub(request);
        break;
      default:
        throw new BadRequestException('Unsupported export format');
    }

    this.eventBus.publish(new FinancialReportExportedEvent(
      storeId, 0, userId, \`\${request.report_type}_\${Date.now()}\`, 'export', {
        format: request.format,
        report_type: request.report_type
      }
    ));

    return result;
  }

  private generateJson(request: ExportRequest): ExportResult {
    const payload = {
      metadata: request.metadata,
      data: request.data
    };
    return {
      format: 'JSON',
      mime_type: 'application/json',
      file_name: \`\${request.report_type}_\${Date.now()}.json\`,
      content: JSON.stringify(payload, null, 2)
    };
  }

  private generateCsv(request: ExportRequest): ExportResult {
    const { metadata, data } = request;
    let csv = \`\${metadata.company_name}\\n\`;
    csv += \`\${metadata.report_name}\\n\`;
    csv += \`Period: \${metadata.fiscal_period}\\n\`;
    csv += \`Generated By: \${metadata.generated_by} on \${metadata.generated_date.toISOString()}\\n\\n\`;

    // Extremely generic CSV flattener
    if (Array.isArray(data) && data.length > 0) {
      const keys = Object.keys(data[0]);
      csv += keys.join(',') + '\\n';
      for (const row of data) {
        csv += keys.map(k => {
          let val = row[k];
          if (val === null || val === undefined) return '';
          if (typeof val === 'string' && (val.includes(',') || val.includes('\\n'))) {
            return \`"\${val.replace(/"/g, '""')}"\`;
          }
          return val;
        }).join(',') + '\\n';
      }
    } else {
      csv += 'No detailed tabular data provided or unsupported format for generic CSV.\\n';
    }

    return {
      format: 'CSV',
      mime_type: 'text/csv',
      file_name: \`\${request.report_type}_\${Date.now()}.csv\`,
      content: csv
    };
  }

  private generateStub(request: ExportRequest): ExportResult {
    return {
      format: request.format,
      mime_type: 'text/plain',
      file_name: \`\${request.report_type}_\${Date.now()}.\${request.format.toLowerCase()}\`,
      content: \`\${request.format} generation is future-ready. Please install required libraries (e.g. exceljs, pdfkit).\`
    };
  }
}
`,

  // Controllers
  'controllers/financial-export.controller.ts': `import { Controller, Post, Body, Req, Res } from '@nestjs/common';
import { FinancialExportService } from '../services/financial-export.service';
import { ExportRequest } from '../interfaces/financial-export.interface';

@Controller('accounting/export')
export class FinancialExportController {
  constructor(private readonly exportService: FinancialExportService) {}

  @Post()
  async exportReport(@Body() request: ExportRequest, @Req() req: any, @Res() res: any) {
    const storeId = req.body.store_id || 1;
    const userId = req.user?.id || 1;

    const result = await this.exportService.generateExport(request, storeId, userId);

    res.setHeader('Content-Type', result.mime_type);
    res.setHeader('Content-Disposition', \`attachment; filename="\${result.file_name}"\`);
    return res.send(result.content);
  }
}
`
};

for (const [relativePath, content] of Object.entries(files)) {
  const fullPath = path.join(basePath, relativePath);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, content, 'utf8');
  console.log('Created:', relativePath);
}
