export const EVENT_REGISTRY = {
  VOUCHER_APPROVED: 'VOUCHER_APPROVED',
  JOURNAL_ENTRY_POSTED: 'JOURNAL_ENTRY_POSTED',
  POSTING_COMPLETED: 'POSTING_COMPLETED',
  POSTING_FAILED: 'POSTING_FAILED',
};
