import { BusinessEvent } from '../enums/business-event.enum';
import { AccountingEventContract } from '../contracts/accounting-event.contract';

export const ACCOUNTING_EVENT_MAPPING: Record<BusinessEvent, AccountingEventContract> = {
  [BusinessEvent.POS_SALE]: {
    event: BusinessEvent.POS_SALE,
    voucher_type_code: 'CASH_RECEIPT_VOUCHER',
    journal_type_code: 'SALES_JNL',
    required_system_accounts: ['CASH_IN_HAND', 'SALES_REVENUE'],
    auto_posting: true,
    approval_workflow_code: 'AUTO_APPROVE',
  },
  [BusinessEvent.POS_REFUND]: {
    event: BusinessEvent.POS_REFUND,
    voucher_type_code: 'CASH_PAYMENT_VOUCHER',
    journal_type_code: 'SALES_JNL',
    required_system_accounts: ['CASH_IN_HAND', 'SALES_RETURNS'],
    auto_posting: true,
    approval_workflow_code: 'AUTO_APPROVE',
  },
  [BusinessEvent.POS_VOID]: {
    event: BusinessEvent.POS_VOID,
    voucher_type_code: 'JOURNAL_VOUCHER',
    journal_type_code: 'SALES_JNL',
    required_system_accounts: ['CASH_IN_HAND', 'SALES_REVENUE'],
    auto_posting: false,
    approval_workflow_code: 'MANAGER_APPROVE',
  },
  [BusinessEvent.PURCHASE_INVOICE]: {
    event: BusinessEvent.PURCHASE_INVOICE,
    voucher_type_code: 'JOURNAL_VOUCHER',
    journal_type_code: 'PURCHASE_JNL',
    required_system_accounts: ['INVENTORY_ASSET', 'ACCOUNTS_PAYABLE'],
    auto_posting: false,
    approval_workflow_code: 'MANAGER_APPROVE',
  },
  [BusinessEvent.PURCHASE_RETURN]: {
    event: BusinessEvent.PURCHASE_RETURN,
    voucher_type_code: 'DEBIT_NOTE',
    journal_type_code: 'PURCHASE_JNL',
    required_system_accounts: ['ACCOUNTS_PAYABLE', 'INVENTORY_ASSET'],
    auto_posting: false,
    approval_workflow_code: 'MANAGER_APPROVE',
  },
  [BusinessEvent.GOODS_RECEIPT]: {
    event: BusinessEvent.GOODS_RECEIPT,
    voucher_type_code: 'JOURNAL_VOUCHER',
    journal_type_code: 'INVENTORY_JNL',
    required_system_accounts: ['INVENTORY_ASSET', 'GOODS_RECEIVED_NOT_INVOICED'],
    auto_posting: true,
    approval_workflow_code: 'AUTO_APPROVE',
  },
  [BusinessEvent.INVENTORY_ADJUSTMENT]: {
    event: BusinessEvent.INVENTORY_ADJUSTMENT,
    voucher_type_code: 'JOURNAL_VOUCHER',
    journal_type_code: 'INVENTORY_JNL',
    required_system_accounts: ['INVENTORY_ASSET', 'INVENTORY_SHRINKAGE'],
    auto_posting: false,
    approval_workflow_code: 'MANAGER_APPROVE',
  },
  [BusinessEvent.INVENTORY_CONSUMPTION]: {
    event: BusinessEvent.INVENTORY_CONSUMPTION,
    voucher_type_code: 'JOURNAL_VOUCHER',
    journal_type_code: 'INVENTORY_JNL',
    required_system_accounts: ['COST_OF_GOODS_SOLD', 'INVENTORY_ASSET'],
    auto_posting: true,
    approval_workflow_code: 'AUTO_APPROVE',
  },
  [BusinessEvent.INVENTORY_TRANSFER]: {
    event: BusinessEvent.INVENTORY_TRANSFER,
    voucher_type_code: 'JOURNAL_VOUCHER',
    journal_type_code: 'INVENTORY_JNL',
    required_system_accounts: ['INVENTORY_ASSET_TRANSIT', 'INVENTORY_ASSET'],
    auto_posting: false,
    approval_workflow_code: 'MANAGER_APPROVE',
  },
  [BusinessEvent.PAYROLL_APPROVED]: {
    event: BusinessEvent.PAYROLL_APPROVED,
    voucher_type_code: 'JOURNAL_VOUCHER',
    journal_type_code: 'PAYROLL_JNL',
    required_system_accounts: ['SALARY_EXPENSE', 'SALARY_PAYABLE'],
    auto_posting: false,
    approval_workflow_code: 'FINANCE_APPROVE',
  },
  [BusinessEvent.SALARY_PAID]: {
    event: BusinessEvent.SALARY_PAID,
    voucher_type_code: 'BANK_PAYMENT_VOUCHER',
    journal_type_code: 'CASH_PAYMENT_JNL',
    required_system_accounts: ['SALARY_PAYABLE', 'BANK_ACCOUNT'],
    auto_posting: false,
    approval_workflow_code: 'FINANCE_APPROVE',
  },
  [BusinessEvent.CUSTOMER_PAYMENT]: {
    event: BusinessEvent.CUSTOMER_PAYMENT,
    voucher_type_code: 'CASH_RECEIPT_VOUCHER',
    journal_type_code: 'CASH_RECEIPT_JNL',
    required_system_accounts: ['CASH_IN_HAND', 'ACCOUNTS_RECEIVABLE'],
    auto_posting: true,
    approval_workflow_code: 'AUTO_APPROVE',
  },
  [BusinessEvent.VENDOR_PAYMENT]: {
    event: BusinessEvent.VENDOR_PAYMENT,
    voucher_type_code: 'BANK_PAYMENT_VOUCHER',
    journal_type_code: 'CASH_PAYMENT_JNL',
    required_system_accounts: ['ACCOUNTS_PAYABLE', 'BANK_ACCOUNT'],
    auto_posting: false,
    approval_workflow_code: 'FINANCE_APPROVE',
  },
  [BusinessEvent.BANK_DEPOSIT]: {
    event: BusinessEvent.BANK_DEPOSIT,
    voucher_type_code: 'CONTRA_VOUCHER',
    journal_type_code: 'BANK_JNL',
    required_system_accounts: ['BANK_ACCOUNT', 'CASH_IN_HAND'],
    auto_posting: true,
    approval_workflow_code: 'AUTO_APPROVE',
  },
  [BusinessEvent.BANK_WITHDRAWAL]: {
    event: BusinessEvent.BANK_WITHDRAWAL,
    voucher_type_code: 'CONTRA_VOUCHER',
    journal_type_code: 'BANK_JNL',
    required_system_accounts: ['CASH_IN_HAND', 'BANK_ACCOUNT'],
    auto_posting: false,
    approval_workflow_code: 'MANAGER_APPROVE',
  },
  [BusinessEvent.SUBSCRIPTION_ACTIVATED]: {
    event: BusinessEvent.SUBSCRIPTION_ACTIVATED,
    voucher_type_code: 'JOURNAL_VOUCHER',
    journal_type_code: 'SALES_JNL',
    required_system_accounts: ['ACCOUNTS_RECEIVABLE', 'DEFERRED_REVENUE'],
    auto_posting: true,
    approval_workflow_code: 'AUTO_APPROVE',
  },
  [BusinessEvent.SUBSCRIPTION_RENEWED]: {
    event: BusinessEvent.SUBSCRIPTION_RENEWED,
    voucher_type_code: 'JOURNAL_VOUCHER',
    journal_type_code: 'SALES_JNL',
    required_system_accounts: ['ACCOUNTS_RECEIVABLE', 'DEFERRED_REVENUE'],
    auto_posting: true,
    approval_workflow_code: 'AUTO_APPROVE',
  },
  [BusinessEvent.SUBSCRIPTION_CANCELLED]: {
    event: BusinessEvent.SUBSCRIPTION_CANCELLED,
    voucher_type_code: 'JOURNAL_VOUCHER',
    journal_type_code: 'SALES_JNL',
    required_system_accounts: ['DEFERRED_REVENUE', 'SALES_REVENUE'],
    auto_posting: true,
    approval_workflow_code: 'AUTO_APPROVE',
  },
  [BusinessEvent.ASSET_PURCHASE]: {
    event: BusinessEvent.ASSET_PURCHASE,
    voucher_type_code: 'JOURNAL_VOUCHER',
    journal_type_code: 'GENERAL_JNL',
    required_system_accounts: ['FIXED_ASSET', 'BANK_ACCOUNT'],
    auto_posting: false,
    approval_workflow_code: 'FINANCE_APPROVE',
  },
  [BusinessEvent.ASSET_DISPOSAL]: {
    event: BusinessEvent.ASSET_DISPOSAL,
    voucher_type_code: 'JOURNAL_VOUCHER',
    journal_type_code: 'GENERAL_JNL',
    required_system_accounts: ['BANK_ACCOUNT', 'FIXED_ASSET', 'GAIN_LOSS_ASSET'],
    auto_posting: false,
    approval_workflow_code: 'FINANCE_APPROVE',
  },
  [BusinessEvent.MANUAL_JOURNAL]: {
    event: BusinessEvent.MANUAL_JOURNAL,
    voucher_type_code: 'JV',
    journal_type_code: 'GEN',
    required_system_accounts: [],
    auto_posting: false,
    approval_workflow_code: 'WF-ACC-MANUAL',
  },
  [BusinessEvent.STOCK_GAIN]: {
    event: BusinessEvent.STOCK_GAIN,
    voucher_type_code: 'INV-ADJ',
    journal_type_code: 'INV',
    required_system_accounts: ['Inventory Asset', 'Inventory Gain'],
    auto_posting: true,
    approval_workflow_code: 'WF-INV-ADJ',
  },
  [BusinessEvent.STOCK_LOSS]: {
    event: BusinessEvent.STOCK_LOSS,
    voucher_type_code: 'INV-ADJ',
    journal_type_code: 'INV',
    required_system_accounts: ['Inventory Asset', 'Inventory Loss'],
    auto_posting: true,
    approval_workflow_code: 'WF-INV-ADJ',
  },
  [BusinessEvent.WASTE_POSTING]: {
    event: BusinessEvent.WASTE_POSTING,
    voucher_type_code: 'INV-WST',
    journal_type_code: 'INV',
    required_system_accounts: ['Inventory Asset', 'Inventory Waste Expense'],
    auto_posting: true,
    approval_workflow_code: 'WF-INV-WST',
  },
  [BusinessEvent.PRODUCTION_CONSUMPTION]: {
    event: BusinessEvent.PRODUCTION_CONSUMPTION,
    voucher_type_code: 'INV-PROD',
    journal_type_code: 'INV',
    required_system_accounts: ['Inventory Asset', 'WIP Inventory'],
    auto_posting: true,
    approval_workflow_code: 'WF-PROD',
  },
  [BusinessEvent.PRODUCTION_OUTPUT]: {
    event: BusinessEvent.PRODUCTION_OUTPUT,
    voucher_type_code: 'INV-PROD',
    journal_type_code: 'INV',
    required_system_accounts: ['WIP Inventory', 'Inventory Asset'],
    auto_posting: true,
    approval_workflow_code: 'WF-PROD',
  },
  [BusinessEvent.PRODUCTION_VARIANCE]: {
    event: BusinessEvent.PRODUCTION_VARIANCE,
    voucher_type_code: 'INV-PROD-VAR',
    journal_type_code: 'INV',
    required_system_accounts: ['Production Variance Expense', 'Production Gain'],
    auto_posting: true,
    approval_workflow_code: 'WF-PROD-VAR',
  },
};
