import { BusinessModule } from '../enums/business-module.enum';
import { BusinessEvent } from '../enums/business-event.enum';
import { BusinessEventContract } from '../contracts/business-event.contract';

export const BUSINESS_EVENT_CATALOG: Record<BusinessEvent, BusinessEventContract> = {
  [BusinessEvent.POS_SALE]: {
    module: BusinessModule.POS,
    event: BusinessEvent.POS_SALE,
    document_type: 'Order',
    document_id_prefix: 'ORD',
    posting_required: true,
    approval_required: false,
    default_currency: 'PKR',
    default_journal_code: 'SALES_JNL',
    accounting_rule_code: 'RULE_POS_SALE',
    is_active: true,
  },
  [BusinessEvent.POS_REFUND]: {
    module: BusinessModule.POS,
    event: BusinessEvent.POS_REFUND,
    document_type: 'Order',
    document_id_prefix: 'RFD',
    posting_required: true,
    approval_required: true,
    default_currency: 'PKR',
    default_journal_code: 'SALES_JNL',
    accounting_rule_code: 'RULE_POS_REFUND',
    is_active: true,
  },
  [BusinessEvent.POS_VOID]: {
    module: BusinessModule.POS,
    event: BusinessEvent.POS_VOID,
    document_type: 'Order',
    document_id_prefix: 'VOID',
    posting_required: true,
    approval_required: true,
    default_currency: 'PKR',
    default_journal_code: 'SALES_JNL',
    accounting_rule_code: 'RULE_POS_VOID',
    is_active: true,
  },
  [BusinessEvent.PURCHASE_INVOICE]: {
    module: BusinessModule.PURCHASING,
    event: BusinessEvent.PURCHASE_INVOICE,
    document_type: 'Invoice',
    document_id_prefix: 'PINV',
    posting_required: true,
    approval_required: true,
    default_currency: 'PKR',
    default_journal_code: 'PURCHASE_JNL',
    accounting_rule_code: 'RULE_PURCHASE_INVOICE',
    is_active: true,
  },
  [BusinessEvent.PURCHASE_RETURN]: {
    module: BusinessModule.PURCHASING,
    event: BusinessEvent.PURCHASE_RETURN,
    document_type: 'Return',
    document_id_prefix: 'PRET',
    posting_required: true,
    approval_required: true,
    default_currency: 'PKR',
    default_journal_code: 'PURCHASE_JNL',
    accounting_rule_code: 'RULE_PURCHASE_RETURN',
    is_active: true,
  },
  [BusinessEvent.GOODS_RECEIPT]: {
    module: BusinessModule.INVENTORY,
    event: BusinessEvent.GOODS_RECEIPT,
    document_type: 'Receipt',
    document_id_prefix: 'GRN',
    posting_required: true,
    approval_required: false,
    default_currency: 'PKR',
    default_journal_code: 'INVENTORY_JNL',
    accounting_rule_code: 'RULE_GOODS_RECEIPT',
    is_active: true,
  },
  [BusinessEvent.INVENTORY_ADJUSTMENT]: {
    module: BusinessModule.INVENTORY,
    event: BusinessEvent.INVENTORY_ADJUSTMENT,
    document_type: 'Adjustment',
    document_id_prefix: 'IADJ',
    posting_required: true,
    approval_required: true,
    default_currency: 'PKR',
    default_journal_code: 'INVENTORY_JNL',
    accounting_rule_code: 'RULE_INVENTORY_ADJUSTMENT',
    is_active: true,
  },
  [BusinessEvent.INVENTORY_CONSUMPTION]: {
    module: BusinessModule.INVENTORY,
    event: BusinessEvent.INVENTORY_CONSUMPTION,
    document_type: 'Consumption',
    document_id_prefix: 'ICNS',
    posting_required: true,
    approval_required: false,
    default_currency: 'PKR',
    default_journal_code: 'INVENTORY_JNL',
    accounting_rule_code: 'RULE_INVENTORY_CONSUMPTION',
    is_active: true,
  },
  [BusinessEvent.INVENTORY_TRANSFER]: {
    module: BusinessModule.INVENTORY,
    event: BusinessEvent.INVENTORY_TRANSFER,
    document_type: 'Transfer',
    document_id_prefix: 'ITRN',
    posting_required: true,
    approval_required: true,
    default_currency: 'PKR',
    default_journal_code: 'INVENTORY_JNL',
    accounting_rule_code: 'RULE_INVENTORY_TRANSFER',
    is_active: true,
  },
  [BusinessEvent.PAYROLL_APPROVED]: {
    module: BusinessModule.PAYROLL,
    event: BusinessEvent.PAYROLL_APPROVED,
    document_type: 'Payroll',
    document_id_prefix: 'PRL',
    posting_required: true,
    approval_required: true,
    default_currency: 'PKR',
    default_journal_code: 'PAYROLL_JNL',
    accounting_rule_code: 'RULE_PAYROLL_APPROVED',
    is_active: true,
  },
  [BusinessEvent.SALARY_PAID]: {
    module: BusinessModule.PAYROLL,
    event: BusinessEvent.SALARY_PAID,
    document_type: 'Payment',
    document_id_prefix: 'PAY',
    posting_required: true,
    approval_required: true,
    default_currency: 'PKR',
    default_journal_code: 'CASH_PAYMENT_JNL',
    accounting_rule_code: 'RULE_SALARY_PAID',
    is_active: true,
  },
  [BusinessEvent.CUSTOMER_PAYMENT]: {
    module: BusinessModule.SALES,
    event: BusinessEvent.CUSTOMER_PAYMENT,
    document_type: 'Receipt',
    document_id_prefix: 'RCP',
    posting_required: true,
    approval_required: false,
    default_currency: 'PKR',
    default_journal_code: 'CASH_RECEIPT_JNL',
    accounting_rule_code: 'RULE_CUSTOMER_PAYMENT',
    is_active: true,
  },
  [BusinessEvent.VENDOR_PAYMENT]: {
    module: BusinessModule.PURCHASING,
    event: BusinessEvent.VENDOR_PAYMENT,
    document_type: 'Payment',
    document_id_prefix: 'VPAY',
    posting_required: true,
    approval_required: true,
    default_currency: 'PKR',
    default_journal_code: 'CASH_PAYMENT_JNL',
    accounting_rule_code: 'RULE_VENDOR_PAYMENT',
    is_active: true,
  },
  [BusinessEvent.BANK_DEPOSIT]: {
    module: BusinessModule.ACCOUNTING,
    event: BusinessEvent.BANK_DEPOSIT,
    document_type: 'Deposit',
    document_id_prefix: 'BDEP',
    posting_required: true,
    approval_required: false,
    default_currency: 'PKR',
    default_journal_code: 'BANK_JNL',
    accounting_rule_code: 'RULE_BANK_DEPOSIT',
    is_active: true,
  },
  [BusinessEvent.BANK_WITHDRAWAL]: {
    module: BusinessModule.ACCOUNTING,
    event: BusinessEvent.BANK_WITHDRAWAL,
    document_type: 'Withdrawal',
    document_id_prefix: 'BWTH',
    posting_required: true,
    approval_required: true,
    default_currency: 'PKR',
    default_journal_code: 'BANK_JNL',
    accounting_rule_code: 'RULE_BANK_WITHDRAWAL',
    is_active: true,
  },
  [BusinessEvent.SUBSCRIPTION_ACTIVATED]: {
    module: BusinessModule.SUBSCRIPTION,
    event: BusinessEvent.SUBSCRIPTION_ACTIVATED,
    document_type: 'Subscription',
    document_id_prefix: 'SUB',
    posting_required: true,
    approval_required: false,
    default_currency: 'PKR',
    default_journal_code: 'SALES_JNL',
    accounting_rule_code: 'RULE_SUB_ACTIVATED',
    is_active: true,
  },
  [BusinessEvent.SUBSCRIPTION_RENEWED]: {
    module: BusinessModule.SUBSCRIPTION,
    event: BusinessEvent.SUBSCRIPTION_RENEWED,
    document_type: 'Subscription',
    document_id_prefix: 'SREN',
    posting_required: true,
    approval_required: false,
    default_currency: 'PKR',
    default_journal_code: 'SALES_JNL',
    accounting_rule_code: 'RULE_SUB_RENEWED',
    is_active: true,
  },
  [BusinessEvent.SUBSCRIPTION_CANCELLED]: {
    module: BusinessModule.SUBSCRIPTION,
    event: BusinessEvent.SUBSCRIPTION_CANCELLED,
    document_type: 'Subscription',
    document_id_prefix: 'SCAN',
    posting_required: true,
    approval_required: false,
    default_currency: 'PKR',
    default_journal_code: 'SALES_JNL',
    accounting_rule_code: 'RULE_SUB_CANCELLED',
    is_active: true,
  },
  [BusinessEvent.ASSET_PURCHASE]: {
    module: BusinessModule.ASSETS,
    event: BusinessEvent.ASSET_PURCHASE,
    document_type: 'Asset',
    document_id_prefix: 'AST',
    posting_required: true,
    approval_required: true,
    default_currency: 'PKR',
    default_journal_code: 'GENERAL_JNL',
    accounting_rule_code: 'RULE_ASSET_PURCHASE',
    is_active: true,
  },
  [BusinessEvent.ASSET_DISPOSAL]: {
    module: BusinessModule.ASSETS,
    event: BusinessEvent.ASSET_DISPOSAL,
    document_type: 'Asset',
    document_id_prefix: 'ADSP',
    posting_required: true,
    approval_required: true,
    default_currency: 'PKR',
    default_journal_code: 'GENERAL_JNL',
    accounting_rule_code: 'RULE_ASSET_DISPOSAL',
    is_active: true,
  },
  [BusinessEvent.MANUAL_JOURNAL]: {
    module: BusinessModule.ACCOUNTING,
    event: BusinessEvent.MANUAL_JOURNAL,
    document_type: 'Manual Journal Entry',
    document_id_prefix: 'JV',
    posting_required: true,
    approval_required: true,
    default_currency: 'PKR',
    default_journal_code: 'GEN',
    accounting_rule_code: 'AR-ACC-MANUAL',
    is_active: true,
  },
  [BusinessEvent.STOCK_GAIN]: {
    module: BusinessModule.INVENTORY,
    event: BusinessEvent.STOCK_GAIN,
    document_type: 'Stock Gain',
    document_id_prefix: 'STG',
    posting_required: true,
    approval_required: true,
    default_currency: 'PKR',
    default_journal_code: 'INV',
    accounting_rule_code: 'AR-INV-GAIN',
    is_active: true,
  },
  [BusinessEvent.STOCK_LOSS]: {
    module: BusinessModule.INVENTORY,
    event: BusinessEvent.STOCK_LOSS,
    document_type: 'Stock Loss',
    document_id_prefix: 'STL',
    posting_required: true,
    approval_required: true,
    default_currency: 'PKR',
    default_journal_code: 'INV',
    accounting_rule_code: 'AR-INV-LOSS',
    is_active: true,
  },
  [BusinessEvent.WASTE_POSTING]: {
    module: BusinessModule.INVENTORY,
    event: BusinessEvent.WASTE_POSTING,
    document_type: 'Waste & Spoilage',
    document_id_prefix: 'WST',
    posting_required: true,
    approval_required: true,
    default_currency: 'PKR',
    default_journal_code: 'INV',
    accounting_rule_code: 'AR-INV-WASTE',
    is_active: true,
  },
  [BusinessEvent.PRODUCTION_CONSUMPTION]: {
    module: BusinessModule.INVENTORY,
    event: BusinessEvent.PRODUCTION_CONSUMPTION,
    document_type: 'Production Consumption',
    document_id_prefix: 'PRC',
    posting_required: true,
    approval_required: false,
    default_currency: 'PKR',
    default_journal_code: 'INV',
    accounting_rule_code: 'AR-PROD-CONS',
    is_active: true,
  },
  [BusinessEvent.PRODUCTION_OUTPUT]: {
    module: BusinessModule.INVENTORY,
    event: BusinessEvent.PRODUCTION_OUTPUT,
    document_type: 'Production Output',
    document_id_prefix: 'PRO',
    posting_required: true,
    approval_required: false,
    default_currency: 'PKR',
    default_journal_code: 'INV',
    accounting_rule_code: 'AR-PROD-OUT',
    is_active: true,
  },
  [BusinessEvent.PRODUCTION_VARIANCE]: {
    module: BusinessModule.INVENTORY,
    event: BusinessEvent.PRODUCTION_VARIANCE,
    document_type: 'Production Variance',
    document_id_prefix: 'PRV',
    posting_required: true,
    approval_required: false,
    default_currency: 'PKR',
    default_journal_code: 'INV',
    accounting_rule_code: 'AR-PROD-VAR',
    is_active: true,
  },
};
