export const ACCOUNTING_EVENTS = {
  // Sales
  ORDER_SETTLED_CASH: 'ORDER_SETTLED_CASH',
  ORDER_SETTLED_CARD: 'ORDER_SETTLED_CARD',
  ORDER_SETTLED_CREDIT: 'ORDER_SETTLED_CREDIT',
  ORDER_SETTLED_SPLIT: 'ORDER_SETTLED_SPLIT',
  ORDER_REFUNDED: 'ORDER_REFUNDED',
  ORDER_RETURNED: 'ORDER_RETURNED',
  
  // Inventory
  INVENTORY_RECEIVED: 'INVENTORY_RECEIVED',
  ORDER_DISPATCHED: 'ORDER_DISPATCHED',
  STOCK_WASTED: 'STOCK_WASTED',
  STOCK_DAMAGED: 'STOCK_DAMAGED',
  STOCK_ADJUSTED_UP: 'STOCK_ADJUSTED_UP',
  STOCK_ADJUSTED_DOWN: 'STOCK_ADJUSTED_DOWN',
  STOCK_TRANSFERRED: 'STOCK_TRANSFERRED',
  OPENING_STOCK_POSTED: 'OPENING_STOCK_POSTED',
  
  // Purchasing
  VENDOR_INVOICE_RCVD: 'VENDOR_INVOICE_RCVD',
  VENDOR_PAYMENT_MADE: 'VENDOR_PAYMENT_MADE',
  PO_RETURNED: 'PO_RETURNED',
  
  // Cash & Banking
  CASH_DEPOSITED: 'CASH_DEPOSITED',
  CASH_WITHDRAWN: 'CASH_WITHDRAWN',
  BANK_TRANSFERRED: 'BANK_TRANSFERRED',
  
  // Payroll
  PAYROLL_GENERATED: 'PAYROLL_GENERATED',
  SALARY_DISBURSED: 'SALARY_DISBURSED',
  
  // SaaS
  SUBSCRIPTION_BOUGHT: 'SUBSCRIPTION_BOUGHT',
  SUBSCRIPTION_RENEWED: 'SUBSCRIPTION_RENEWED',
  INVOICE_GENERATED: 'INVOICE_GENERATED',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  
  // Period
  PERIOD_CLOSED: 'PERIOD_CLOSED',
  YEAR_CLOSED: 'YEAR_CLOSED',
  YEAR_OPENED: 'YEAR_OPENED',
};
