import React, { useState, useEffect } from 'react';
import { io } from 'socket.io-client';
import { Lock, Navigation } from 'lucide-react';
import toast from 'react-hot-toast';
import { BACKEND_URL } from './config/backend';
const socket = io(BACKEND_URL);

const DEVICE_ID_KEY = 'd4u_waiter_device_id';
const SESSION_ID_KEY = 'd4u_waiter_session_id';

function getOrCreateDeviceId(): string {
  let id = localStorage.getItem(DEVICE_ID_KEY);
  if (!id) {
    id = (crypto as any).randomUUID ? crypto.randomUUID() : `dev-${Date.now()}-${Math.random().toString(16).slice(2)}`;
    localStorage.setItem(DEVICE_ID_KEY, id);
  }
  return id;
}

interface Props {
  onAuthenticated: (user: any) => void;
}

export default function WaiterTerminalLogin({ onAuthenticated }: Props) {
  const [pin, setPin] = useState('');
  const [deviceName, setDeviceName] = useState('Waiter Tablet');
  const [loading, setLoading] = useState(false);
  const [resuming, setResuming] = useState(true);

  // Refreshing/reopening the browser on an already-paired device resumes the
  // existing session automatically — no PIN re-entry, no disconnect.
  useEffect(() => {
    const storedSessionId = localStorage.getItem(SESSION_ID_KEY);
    if (!storedSessionId) {
      setResuming(false);
      return;
    }
    const deviceId = getOrCreateDeviceId();

    socket.emitWithAck('resume_waiter_session', { session_id: Number(storedSessionId), device_id: deviceId })
      .then((response: any) => {
        if (response?.success) {
          // Lets this tablet call JWT-gated REST endpoints (e.g. POST
          // /pos-orders to send an order) — without this, every such call
          // 401s since terminal pairing itself never issued a token before.
          if (response.access_token) localStorage.setItem('d4u_pos_token', response.access_token);
          onAuthenticated({
            name: response.waiter_name || response.device_name || 'Waiter Tablet',
            role: 'Waiter',
            store_id: response.store_id,
            sessionId: response.session_id,
            deviceId,
          });
        } else {
          localStorage.removeItem(SESSION_ID_KEY);
          setResuming(false);
        }
      })
      .catch(() => setResuming(false));
  }, [onAuthenticated]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!pin) return toast.error('Enter a valid PIN');

    setLoading(true);
    const deviceId = getOrCreateDeviceId();

    try {
      const response = await socket.emitWithAck('auth_waiter_pin', { pin, device_id: deviceId, device_name: deviceName || 'Waiter Tablet' });
      if (response && response.success) {
        toast.success('Connected to POS successfully!');
        localStorage.setItem(SESSION_ID_KEY, String(response.session_id));
        if (response.access_token) localStorage.setItem('d4u_pos_token', response.access_token);
        onAuthenticated({
          name: response.waiter_name || deviceName || 'Waiter Tablet',
          role: 'Waiter',
          store_id: response.store_id,
          terminalPin: pin,
          sessionId: response.session_id,
          deviceId,
        });
      } else {
        toast.error(response?.message || 'Invalid Waiter PIN');
      }
    } catch (err) {
      toast.error('Network error validating PIN');
    } finally {
      setLoading(false);
    }
  };

  if (resuming) {
    return (
      <div className="h-screen bg-slate-900 flex items-center justify-center p-4">
        <p className="text-slate-400 text-sm">Reconnecting to POS...</p>
      </div>
    );
  }

  return (
    <div className="h-screen bg-slate-900 flex items-center justify-center p-4">
      <div className="bg-slate-800 p-8 rounded-3xl border border-slate-700 w-full max-w-sm shadow-2xl relative overflow-hidden">
        <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-blue-500 to-indigo-500"></div>
        <div className="flex justify-center mb-6">
          <div className="w-20 h-20 bg-indigo-500/20 text-indigo-400 rounded-full flex items-center justify-center">
            <Navigation size={40} />
          </div>
        </div>
        <h2 className="text-3xl font-black text-white text-center mb-2">Tablet Pairing</h2>
        <p className="text-slate-400 text-sm text-center mb-8">Enter the PIN generated by the Cashier POS to link this device.</p>

        <form onSubmit={handleSubmit} className="space-y-6">
          <div>
            <label className="block text-xs font-bold text-slate-400 mb-2 uppercase tracking-wider">Pairing PIN</label>
            <input
              type="text"
              value={pin}
              onChange={e => setPin(e.target.value)}
              className="w-full bg-slate-900 border-2 border-slate-700 rounded-2xl p-4 text-white text-center text-3xl font-black tracking-widest focus:border-indigo-500 focus:outline-none transition-colors"
              placeholder="0000"
              required
              autoFocus
            />
          </div>
          <div>
            <label className="block text-xs font-bold text-slate-400 mb-2 uppercase tracking-wider">Device Name</label>
            <input
              type="text"
              value={deviceName}
              onChange={e => setDeviceName(e.target.value)}
              className="w-full bg-slate-900 border-2 border-slate-700 rounded-xl p-3 text-white text-center font-bold focus:border-indigo-500 focus:outline-none transition-colors"
              placeholder="e.g. Rooftop Tablet 01"
            />
          </div>
          <button
            type="submit"
            disabled={loading}
            className="w-full bg-indigo-500 hover:bg-indigo-600 text-white font-bold py-4 rounded-xl transition-all shadow-lg hover:-translate-y-1 disabled:opacity-50"
          >
            {loading ? 'Verifying...' : 'Link Tablet'}
          </button>
        </form>
      </div>
    </div>
  );
}
