import { Controller, Get, Query, Req, ParseIntPipe } from '@nestjs/common';
import { RequirePermissions } from '../../../../common/decorators';
import { BalanceSheetService } from '../services/balance-sheet.service';
import { BalanceSheetFilter } from '../interfaces/balance-sheet-filter.interface';
import { getSessionUserId } from '../../../../common/utils/session-context.util';

@Controller('accounting/balance-sheet')
export class BalanceSheetController {
  constructor(private readonly bsService: BalanceSheetService) {}

  @RequirePermissions('finance.reports.view')
  @Get()
  async getBalanceSheet(@Query() query: any, @Req() req: any) {
    const filter: BalanceSheetFilter = {
      fiscal_year_id: Number(query.fiscal_year_id),
      accounting_period_id: query.accounting_period_id ? Number(query.accounting_period_id) : undefined,
      date: new Date(query.date),
      store_id: Number(query.store_id),
    };
    const userId = getSessionUserId(req.user); 
    return this.bsService.generateBalanceSheet(filter, userId);
  }

  @RequirePermissions('finance.reports.export')
  @Get('export')
  async exportBalanceSheet(@Query() query: any, @Req() req: any) {
    const filter: BalanceSheetFilter = {
      fiscal_year_id: Number(query.fiscal_year_id),
      date: new Date(query.date),
      store_id: Number(query.store_id),
    };
    const userId = getSessionUserId(req.user);
    const result = await this.bsService.generateBalanceSheet(filter, userId);
    
    let csv = `Balance Sheet Statement - ${result.statement_name}\n`;
    csv += `As of: ${result.date.toISOString().split('T')[0]}\n\n`;
    
    csv += 'Section,Amount\n';
    
    const printSection = (sec: any, indent: string) => {
       csv += `${indent}${sec.name},${sec.total_amount}\n`;
       for (const sub of sec.sub_sections) {
         printSection(sub, indent + '  ');
       }
       for (const line of sec.lines) {
         csv += `${indent}  ${line.code} ${line.name},${line.amount}\n`;
       }
    };

    csv += 'ASSETS\n';
    result.asset_sections.forEach(s => printSection(s, '  '));
    csv += `TOTAL ASSETS,${result.total_assets}\n\n`;

    csv += 'LIABILITIES\n';
    result.liability_sections.forEach(s => printSection(s, '  '));
    csv += `TOTAL LIABILITIES,${result.total_liabilities}\n\n`;

    csv += 'EQUITY\n';
    result.equity_sections.forEach(s => printSection(s, '  '));
    csv += `  Current Year Profit,${result.current_year_profit}\n`;
    csv += `TOTAL EQUITY,${result.total_equity}\n\n`;

    csv += `TOTAL LIABILITIES + EQUITY,${result.total_liabilities_and_equity}\n`;
    csv += `DIFFERENCE,${result.difference}\n\n`;

    csv += `Generated By: ${result.generated_by} on ${result.generated_date.toISOString()}\n`;

    return { type: 'csv', data: csv };
  }
}
