import { Controller, Get, Query, Req, ParseIntPipe } from '@nestjs/common';
import { RequirePermissions } from '../../../../common/decorators';
import { CashFlowService } from '../services/cash-flow.service';
import { CashFlowFilter } from '../interfaces/cash-flow-filter.interface';

@RequirePermissions('finance.accounting.manage')
@Controller('accounting/cash-flow')
export class CashFlowController {
  constructor(private readonly cfService: CashFlowService) {}

  @Get()
  async getCashFlow(@Query() query: any, @Req() req: any) {
    const filter: CashFlowFilter = {
      fiscal_year_id: Number(query.fiscal_year_id),
      accounting_period_id: query.accounting_period_id ? Number(query.accounting_period_id) : undefined,
      start_date: new Date(query.start_date),
      end_date: new Date(query.end_date),
      store_id: Number(query.store_id),
    };
    const userId = req.user?.id || 1; 
    return this.cfService.generateCashFlow(filter, userId);
  }

  @Get('export')
  async exportCashFlow(@Query() query: any, @Req() req: any) {
    const filter: CashFlowFilter = {
      fiscal_year_id: Number(query.fiscal_year_id),
      start_date: new Date(query.start_date),
      end_date: new Date(query.end_date),
      store_id: Number(query.store_id),
    };
    const userId = req.user?.id || 1;
    const result = await this.cfService.generateCashFlow(filter, userId);
    
    let csv = `Cash Flow Statement - ${result.statement_name}\n`;
    csv += `Period: ${result.start_date.toISOString().split('T')[0]} to ${result.end_date.toISOString().split('T')[0]}\n\n`;
    
    csv += 'Section,Amount\n';
    
    const printSection = (sec: any, indent: string) => {
       csv += `${indent}${sec.name},${sec.total_amount}\n`;
       for (const sub of sec.sub_sections) {
         printSection(sub, indent + '  ');
       }
       for (const line of sec.lines) {
         csv += `${indent}  ${line.code} ${line.name},${line.amount}\n`;
       }
    };

    csv += 'OPERATING ACTIVITIES\n';
    result.operating_activities.forEach(s => printSection(s, '  '));
    csv += `Net Cash from Operating Activities,${result.net_operating_cash}\n\n`;

    csv += 'INVESTING ACTIVITIES\n';
    result.investing_activities.forEach(s => printSection(s, '  '));
    csv += `Net Cash from Investing Activities,${result.net_investing_cash}\n\n`;

    csv += 'FINANCING ACTIVITIES\n';
    result.financing_activities.forEach(s => printSection(s, '  '));
    csv += `Net Cash from Financing Activities,${result.net_financing_cash}\n\n`;

    csv += `OPENING CASH BALANCE,${result.opening_cash}\n`;
    csv += `NET CASH MOVEMENT,${result.net_cash_movement}\n`;
    csv += `CLOSING CASH BALANCE,${result.closing_cash}\n\n`;

    csv += `DIFFERENCE (Verification),${result.difference}\n\n`;

    csv += `Generated By: ${result.generated_by} on ${result.generated_date.toISOString()}\n`;

    return { type: 'csv', data: csv };
  }
}
