import { Controller, Get, Query, Req, ParseIntPipe } from '@nestjs/common';
import { RequirePermissions } from '../../../../common/decorators';
import { ProfitLossService } from '../services/profit-loss.service';
import { ProfitLossFilter } from '../interfaces/profit-loss-filter.interface';

@RequirePermissions('finance.accounting.manage')
@Controller('accounting/profit-loss')
export class ProfitLossController {
  constructor(private readonly plService: ProfitLossService) {}

  @Get()
  async getProfitLoss(@Query() query: any, @Req() req: any) {
    const filter: ProfitLossFilter = {
      fiscal_year_id: Number(query.fiscal_year_id),
      accounting_period_id: query.accounting_period_id ? Number(query.accounting_period_id) : undefined,
      start_date: new Date(query.start_date),
      end_date: new Date(query.end_date),
      store_id: Number(query.store_id),
    };
    const userId = req.user?.id || 1; 
    return this.plService.generateProfitLoss(filter, userId);
  }

  @Get('export')
  async exportProfitLoss(@Query() query: any, @Req() req: any) {
    const filter: ProfitLossFilter = {
      fiscal_year_id: Number(query.fiscal_year_id),
      start_date: new Date(query.start_date),
      end_date: new Date(query.end_date),
      store_id: Number(query.store_id),
    };
    const userId = req.user?.id || 1;
    const result = await this.plService.generateProfitLoss(filter, userId);
    
    let csv = `Profit & Loss Statement - ${result.statement_name}\n`;
    csv += `Period: ${result.start_date.toISOString().split('T')[0]} to ${result.end_date.toISOString().split('T')[0]}\n\n`;
    
    csv += 'Section,Amount\n';
    
    const printSection = (sec: any, indent: string) => {
       csv += `${indent}${sec.name},${sec.total_amount}\n`;
       for (const sub of sec.sub_sections) {
         printSection(sub, indent + '  ');
       }
       for (const line of sec.lines) {
         csv += `${indent}  ${line.code} ${line.name},${line.amount}\n`;
       }
    };

    csv += 'REVENUE\n';
    result.revenue_sections.forEach(s => printSection(s, '  '));
    csv += `Total Revenue,${result.total_revenue}\n\n`;

    csv += 'COST OF SALES\n';
    result.cost_of_sales_sections.forEach(s => printSection(s, '  '));
    csv += `Total Cost of Sales,${result.total_cost_of_sales}\n\n`;

    csv += `GROSS PROFIT,${result.gross_profit}\n\n`;

    csv += 'OPERATING EXPENSES\n';
    result.operating_expense_sections.forEach(s => printSection(s, '  '));
    csv += `Total Operating Expenses,${result.total_operating_expenses}\n\n`;

    csv += `OPERATING INCOME,${result.operating_income}\n\n`;

    csv += 'OTHER INCOME\n';
    result.other_income_sections.forEach(s => printSection(s, '  '));
    csv += `Total Other Income,${result.total_other_income}\n\n`;

    csv += 'OTHER EXPENSES\n';
    result.other_expense_sections.forEach(s => printSection(s, '  '));
    csv += `Total Other Expenses,${result.total_other_expenses}\n\n`;

    csv += `NET PROFIT BEFORE TAX,${result.net_profit_before_tax}\n`;
    csv += `TAX EXPENSE,${result.tax_expense}\n`;
    csv += `NET PROFIT,${result.net_profit}\n\n`;

    csv += `Generated By: ${result.generated_by} on ${result.generated_date.toISOString()}\n`;

    return { type: 'csv', data: csv };
  }
}
