import { Injectable, BadRequestException } from '@nestjs/common';
import { DomainEventBusService } from '../events/domain-event-bus.service';
import { FinancialReportExportedEvent } from '../events/financial-report-exported.event';
import { ExportRequest, ExportResult } from '../interfaces/financial-export.interface';

@Injectable()
export class FinancialExportService {
  constructor(private readonly eventBus: DomainEventBusService) {}

  async generateExport(request: ExportRequest, storeId: number, userId: number): Promise<ExportResult> {
    let result: ExportResult;

    switch (request.format) {
      case 'JSON':
        result = this.generateJson(request);
        break;
      case 'CSV':
        result = this.generateCsv(request);
        break;
      case 'EXCEL':
      case 'PDF':
        // Future ready placeholder
        result = this.generateStub(request);
        break;
      default:
        throw new BadRequestException('Unsupported export format');
    }

    this.eventBus.publish(new FinancialReportExportedEvent(
      storeId, 0, userId, `${request.report_type}_${Date.now()}`, 'export', {
        format: request.format,
        report_type: request.report_type
      }
    ));

    return result;
  }

  private generateJson(request: ExportRequest): ExportResult {
    const payload = {
      metadata: request.metadata,
      data: request.data
    };
    return {
      format: 'JSON',
      mime_type: 'application/json',
      file_name: `${request.report_type}_${Date.now()}.json`,
      content: JSON.stringify(payload, null, 2)
    };
  }

  private generateCsv(request: ExportRequest): ExportResult {
    const { metadata, data } = request;
    let csv = `${metadata.company_name}\n`;
    csv += `${metadata.report_name}\n`;
    csv += `Period: ${metadata.fiscal_period}\n`;
    csv += `Generated By: ${metadata.generated_by} on ${metadata.generated_date.toISOString()}\n\n`;

    // Extremely generic CSV flattener
    if (Array.isArray(data) && data.length > 0) {
      const keys = Object.keys(data[0]);
      csv += keys.join(',') + '\n';
      for (const row of data) {
        csv += keys.map(k => {
          let val = row[k];
          if (val === null || val === undefined) return '';
          if (typeof val === 'string' && (val.includes(',') || val.includes('\n'))) {
            return `"${val.replace(/"/g, '""')}"`;
          }
          return val;
        }).join(',') + '\n';
      }
    } else {
      csv += 'No detailed tabular data provided or unsupported format for generic CSV.\n';
    }

    return {
      format: 'CSV',
      mime_type: 'text/csv',
      file_name: `${request.report_type}_${Date.now()}.csv`,
      content: csv
    };
  }

  private generateStub(request: ExportRequest): ExportResult {
    return {
      format: request.format,
      mime_type: 'text/plain',
      file_name: `${request.report_type}_${Date.now()}.${request.format.toLowerCase()}`,
      content: `${request.format} generation is future-ready. Please install required libraries (e.g. exceljs, pdfkit).`
    };
  }
}
